name: recipes_aplazo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network
  http: ^1.2.1
  chucker_flutter: ^1.7.2
  connectivity_plus: ^6.0.3

  # UI
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta-Light.ttf
        - asset: assets/fonts/Recoleta-Regular.ttf
        - asset: assets/fonts/Recoleta-SemiBold.ttf
        - asset: assets/fonts/Recoleta-Bold.ttf
  assets:
      - assets/images/

  uses-material-design: true